version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): update dependency"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: /
    target-branch: master

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): update docker image"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: /
    target-branch: master
