get:
  summary: Get Traefik proxied URLs
  operationId: getTraefikURLs
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: schemas/urls-list.json
    "400":
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: schemas/generic-response.json
